services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    restart: "unless-stopped"
    volumes:
      - type: bind
        source: ./data
        target: /data
      - type: bind
        source: ./data/cache/
        target: /cache/
      - type: bind
        source: .
        target: /data/Data/systems/shadowrun5e/
    environment:
      - CONTAINER_CACHE=/cache/
      - FOUNDRY_ADMIN_KEY=123456789
      - FOUNDRY_UID=1000
      - FOUNDRY_GID=1000
    ports:
      - "30000:30000/tcp"
    secrets:
      - source: config_json
        target: config.json

secrets:
  config_json:
    file: secrets.json
