services:
  foundry:
    image: felddy/foundryvtt:release
    hostname: my_foundry_host
    init: true
    #restart: "unless-stopped"
    volumes:
      - ./data:/data
      - ./data/cache/:/cache/
      - ./system.json:/data/Data/systems/shadowrun5e/system.json
      - ./template.json:/data/Data/systems/shadowrun5e/template.json
      - ./dist:/data/Data/systems/shadowrun5e/dist
      - ./packs:/data/Data/systems/shadowrun5e/packs
      - ./secrets.json:/secrets.json
    environment:
      - CONTAINER_CACHE=/cache/
      - FOUNDRY_ADMIN_KEY=123456789
      - FOUNDRY_UID=1000
      - FOUNDRY_GID=1000
    ports:
      - "30000:30000/tcp"
    secrets:
      - source: config_json
        target: config.json

secrets:
  config_json:
    file: secrets.json
